# Generated by Django 3.2.2 on 2021-07-23 02:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_project_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
